#!/bin/sh
set -e

if [ "$1" = configure ]; then
	update-alternatives --install /bin/csh csh /bin/bsd-csh 30 \
			    --slave /usr/share/man/man1/csh.1.gz csh.1.gz \
				    /usr/share/man/man1/bsd-csh.1.gz

	if which add-shell >/dev/null 2>&1; then
		add-shell /bin/csh
	fi
fi

#DEBHELPER#
